"""add_recon_snapshot_monitoring_alert

Revision ID: 0686d9d188a5
Revises: aa834f32e5ed
Create Date: 2026-05-22 17:04:25.504336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0686d9d188a5'
down_revision: Union[str, Sequence[str], None] = 'aa834f32e5ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_alerts_engagement_id'), 'monitoring_alerts', ['engagement_id'], unique=False)
    op.create_table('recon_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('subdomains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('open_ports', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('endpoints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recon_snapshots_engagement_id'), 'recon_snapshots', ['engagement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recon_snapshots_engagement_id'), table_name='recon_snapshots')
    op.drop_table('recon_snapshots')
    op.drop_index(op.f('ix_monitoring_alerts_engagement_id'), table_name='monitoring_alerts')
    op.drop_table('monitoring_alerts')
    # ### end Alembic commands ###
