"""add_performance_indexes

Revision ID: 1861c1b0307a
Revises: a3c91b7d0e22
Create Date: 2026-05-25 14:24:17.934099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1861c1b0307a'
down_revision: Union[str, Sequence[str], None] = 'a3c91b7d0e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_engagement_id'), 'audit_logs', ['engagement_id'], unique=False)
    op.alter_column('engagements', 'opsec_mode',
               existing_type=sa.BOOLEAN(),
               comment='Enable OPSEC jitter between tool calls',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('engagements', 'request_jitter_ms',
               existing_type=sa.INTEGER(),
               comment='Max random delay (ms) added before each tool request',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_engagements_workspace_id'), 'engagements', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_findings_engagement_id'), 'findings', ['engagement_id'], unique=False)

    # Composite indexes for common query patterns
    op.create_index('ix_findings_engagement_severity', 'findings', ['engagement_id', 'severity'], unique=False)
    op.create_index('ix_findings_engagement_status', 'findings', ['engagement_id', 'status'], unique=False)
    op.create_index('ix_audit_logs_engagement_created', 'audit_logs', ['engagement_id', 'created_at'], unique=False)
    op.create_index('ix_monitoring_alerts_engagement_read', 'monitoring_alerts', ['engagement_id', 'is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_engagement_id'), table_name='findings')
    op.drop_index(op.f('ix_engagements_workspace_id'), table_name='engagements')
    op.drop_index('ix_findings_engagement_severity', table_name='findings')
    op.drop_index('ix_findings_engagement_status', table_name='findings')
    op.drop_index('ix_audit_logs_engagement_created', table_name='audit_logs')
    op.drop_index('ix_monitoring_alerts_engagement_read', table_name='monitoring_alerts')
    op.alter_column('engagements', 'request_jitter_ms',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Max random delay (ms) added before each tool request',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('engagements', 'opsec_mode',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Enable OPSEC jitter between tool calls',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_audit_logs_engagement_id'), table_name='audit_logs')
    # ### end Alembic commands ###
