"""add_workspace_owner_id

Revision ID: aa834f32e5ed
Revises: 6133ff6cb342
Create Date: 2026-05-22 16:21:10.708485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa834f32e5ed'
down_revision: Union[str, Sequence[str], None] = '6133ff6cb342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop LangGraph checkpoint tables if they exist (may not exist on fresh DB)
    op.execute("DROP INDEX IF EXISTS checkpoint_blobs_thread_id_idx")
    op.execute("DROP TABLE IF EXISTS checkpoint_blobs")
    op.execute("DROP INDEX IF EXISTS checkpoint_writes_thread_id_idx")
    op.execute("DROP TABLE IF EXISTS checkpoint_writes")
    op.execute("DROP INDEX IF EXISTS checkpoints_thread_id_idx")
    op.execute("DROP TABLE IF EXISTS checkpoints")
    op.execute("DROP TABLE IF EXISTS checkpoint_migrations")
    # Drop knowledge_records indexes/table if they exist (managed by pentra-knowledge)
    op.execute("DROP INDEX IF EXISTS idx_kr_fts")
    op.execute("DROP INDEX IF EXISTS idx_kr_is_embedded")
    op.execute("DROP INDEX IF EXISTS idx_kr_pentra_tags_gin")
    op.execute("DROP INDEX IF EXISTS idx_kr_program")
    op.execute("DROP INDEX IF EXISTS idx_kr_severity")
    op.execute("DROP INDEX IF EXISTS idx_kr_source_id")
    op.execute("DROP INDEX IF EXISTS idx_kr_tech_stack_gin")
    op.execute("DROP INDEX IF EXISTS idx_kr_vuln_class")
    op.execute("DROP TABLE IF EXISTS knowledge_records")
    op.execute("DROP TABLE IF EXISTS alembic_version")
    op.alter_column('audit_logs', 'actor',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Agent node name or user ID',
               existing_nullable=False)
    op.add_column('workspaces', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_workspaces_owner_id'), 'workspaces', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'workspaces', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_index(op.f('ix_workspaces_owner_id'), table_name='workspaces')
    op.drop_column('workspaces', 'owner_id')
    op.alter_column('audit_logs', 'actor',
               existing_type=sa.VARCHAR(length=100),
               comment='Agent node name or user ID',
               existing_nullable=False)
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.create_table('knowledge_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('vuln_class', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('vuln_subclass', sa.VARCHAR(length=200), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('cvss_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cvss_vector', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('cve_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('program', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('platform_type', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('endpoint_pattern', sa.VARCHAR(length=500), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('http_method', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('auth_required', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('attack_technique', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('attack_steps', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('payload_pattern', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('prerequisites', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('what_tools_missed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chained_with', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('impact', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('impact_category', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('bounty_usd', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('key_insight', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('unique_factor', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('pentra_tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('embedding_model', sa.VARCHAR(length=50), server_default=sa.text("'bge-m3'::character varying"), autoincrement=False, nullable=False),
    sa.Column('embedding_version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('is_embedded', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('full_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_records_pkey'))
    )
    op.create_index(op.f('idx_kr_vuln_class'), 'knowledge_records', ['vuln_class'], unique=False)
    op.create_index(op.f('idx_kr_tech_stack_gin'), 'knowledge_records', ['tech_stack'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_kr_source_id'), 'knowledge_records', ['source_id'], unique=True)
    op.create_index(op.f('idx_kr_severity'), 'knowledge_records', ['severity'], unique=False)
    op.create_index(op.f('idx_kr_program'), 'knowledge_records', ['program'], unique=False)
    op.create_index(op.f('idx_kr_pentra_tags_gin'), 'knowledge_records', ['pentra_tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_kr_is_embedded'), 'knowledge_records', ['is_embedded'], unique=False)
    op.create_index(op.f('idx_kr_fts'), 'knowledge_records', [sa.literal_column("to_tsvector('english'::regconfig, (((COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(attack_technique, ''::text)) || ' '::text) || COALESCE(key_insight, ''::text))")], unique=False, postgresql_using='gin')
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    # ### end Alembic commands ###
