"""add_impact_remediation_to_findings

Revision ID: cc62ee2cd0df
Revises: 5270364c5870
Create Date: 2026-05-26 11:45:04.585079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc62ee2cd0df'
down_revision: Union[str, Sequence[str], None] = '5270364c5870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add impact and remediation columns to findings table."""
    op.add_column('findings', sa.Column('impact', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('remediation', sa.Text(), nullable=True))


def downgrade() -> None:
    """Remove impact and remediation columns from findings table."""
    op.drop_column('findings', 'remediation')
    op.drop_column('findings', 'impact')
    op.drop_table('checkpoints')
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_index(op.f('idx_kr_fts'), table_name='knowledge_records', postgresql_using='gin')
    op.drop_index(op.f('idx_kr_is_embedded'), table_name='knowledge_records')
    op.drop_index(op.f('idx_kr_pentra_tags_gin'), table_name='knowledge_records', postgresql_using='gin')
    op.drop_index(op.f('idx_kr_program'), table_name='knowledge_records')
    op.drop_index(op.f('idx_kr_severity'), table_name='knowledge_records')
    op.drop_index(op.f('idx_kr_source_id'), table_name='knowledge_records')
    op.drop_index(op.f('idx_kr_tech_stack_gin'), table_name='knowledge_records', postgresql_using='gin')
    op.drop_index(op.f('idx_kr_vuln_class'), table_name='knowledge_records')
    op.drop_index(op.f('ix_knowledge_records_quality_score'), table_name='knowledge_records')
    op.drop_table('knowledge_records')
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.drop_table('checkpoint_migrations')
    op.drop_index(op.f('ix_audit_logs_engagement_created'), table_name='audit_logs')
    op.add_column('findings', sa.Column('impact', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('remediation', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_findings_engagement_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_engagement_status'), table_name='findings')
    op.drop_index(op.f('ix_monitoring_alerts_engagement_read'), table_name='monitoring_alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_monitoring_alerts_engagement_read'), 'monitoring_alerts', ['engagement_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_findings_engagement_status'), 'findings', ['engagement_id', 'status'], unique=False)
    op.create_index(op.f('ix_findings_engagement_severity'), 'findings', ['engagement_id', 'severity'], unique=False)
    op.drop_column('findings', 'remediation')
    op.drop_column('findings', 'impact')
    op.create_index(op.f('ix_audit_logs_engagement_created'), 'audit_logs', ['engagement_id', 'created_at'], unique=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('knowledge_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('vuln_class', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('vuln_subclass', sa.VARCHAR(length=200), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('cvss_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cvss_vector', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('cve_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('program', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('platform_type', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('endpoint_pattern', sa.VARCHAR(length=500), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('http_method', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('auth_required', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('attack_technique', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('attack_steps', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('payload_pattern', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('prerequisites', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('what_tools_missed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chained_with', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('impact', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('impact_category', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('bounty_usd', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('key_insight', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('unique_factor', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('pentra_tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=False, comment='Completeness score 0.0-1.0 -- used to boost retrieval rank'),
    sa.Column('embedding_model', sa.VARCHAR(length=50), server_default=sa.text("'bge-m3'::character varying"), autoincrement=False, nullable=False),
    sa.Column('embedding_version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('is_embedded', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('full_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_records_pkey'))
    )
    op.create_index(op.f('ix_knowledge_records_quality_score'), 'knowledge_records', ['quality_score'], unique=False)
    op.create_index(op.f('idx_kr_vuln_class'), 'knowledge_records', ['vuln_class'], unique=False)
    op.create_index(op.f('idx_kr_tech_stack_gin'), 'knowledge_records', ['tech_stack'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_kr_source_id'), 'knowledge_records', ['source_id'], unique=True)
    op.create_index(op.f('idx_kr_severity'), 'knowledge_records', ['severity'], unique=False)
    op.create_index(op.f('idx_kr_program'), 'knowledge_records', ['program'], unique=False)
    op.create_index(op.f('idx_kr_pentra_tags_gin'), 'knowledge_records', ['pentra_tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_kr_is_embedded'), 'knowledge_records', ['is_embedded'], unique=False)
    op.create_index(op.f('idx_kr_fts'), 'knowledge_records', [sa.literal_column("to_tsvector('english'::regconfig, (((COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(attack_technique, ''::text)) || ' '::text) || COALESCE(key_insight, ''::text))")], unique=False, postgresql_using='gin')
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    # ### end Alembic commands ###
